// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV0YBs5rfh9rICBrtKwPB82u62H5WUB_k',
    appId: '1:199936585370:web:b279074f4eb3e50768b923',
    messagingSenderId: '199936585370',
    projectId: 'life-capsule-6b6b5',
    authDomain: 'life-capsule-6b6b5.firebaseapp.com',
    storageBucket: 'life-capsule-6b6b5.appspot.com',
    measurementId: 'G-6B5QP1VQWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4AweTwrAEaIGPZn_F5RKel_3BpyTSb9E',
    appId: '1:199936585370:android:7ff1d647c925f43e68b923',
    messagingSenderId: '199936585370',
    projectId: 'life-capsule-6b6b5',
    storageBucket: 'life-capsule-6b6b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFXhNI8adqCP0nX3NToIASwDDyzMEqj-0',
    appId: '1:199936585370:ios:9231352ca6f4a18f68b923',
    messagingSenderId: '199936585370',
    projectId: 'life-capsule-6b6b5',
    storageBucket: 'life-capsule-6b6b5.appspot.com',
    iosBundleId: 'com.example.lifeCapsule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFXhNI8adqCP0nX3NToIASwDDyzMEqj-0',
    appId: '1:199936585370:ios:9231352ca6f4a18f68b923',
    messagingSenderId: '199936585370',
    projectId: 'life-capsule-6b6b5',
    storageBucket: 'life-capsule-6b6b5.appspot.com',
    iosBundleId: 'com.example.lifeCapsule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV0YBs5rfh9rICBrtKwPB82u62H5WUB_k',
    appId: '1:199936585370:web:ddb1c8325d56a1c968b923',
    messagingSenderId: '199936585370',
    projectId: 'life-capsule-6b6b5',
    authDomain: 'life-capsule-6b6b5.firebaseapp.com',
    storageBucket: 'life-capsule-6b6b5.appspot.com',
    measurementId: 'G-28HMZ06LPY',
  );

}